name: Deploy Trade Store to Github Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      #Checkout Repository
      - name: Checkout code
        uses: actions/checkout@v3

      #Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 24.11.1

      #Install Dependencies
      - name: Install Dependencies
        run: npm install

      #Audit Vulnerabilities
      - name: Audit Vulnerabilities
        run: npm audit

      #Run Lint
      - name: Run Lint
        run: npm run lint

      #Run Test
      - name: Run Test
        run: npm run test

      #Cypress Run
      - name: Start Vite server and run Cypress tests
        run: npm run dev & npx wait-on http://localhost:3000 && npx cypress run

      #Build the project
      - name: Build the project
        run: npm run build

      #Deploy to github Pages
      # - name: Deploy to github Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{secrets.GITHUB_TOKEN}}
